/**
 * Classic-script entry. The maintainer build emits frontend/js/workspace-model.js.
 * The Vue application does not import this module, so the Vue bundle stays free
 * of workspace state. No Vue, Pinia, or Vue Router.
 */
export {
  DEFAULT_MAIN_SPLIT_RATIO,
  MAX_VISIBLE_PANES,
  WORKSPACE_STATE_VERSION,
  clampMainSplitRatio,
  collectLeafTabIds,
  collectSplitIds,
  containsTab,
  findLeafByTabId,
  findNodeById,
  findSiblingLeafTabId,
  isLeaf,
  isSplit,
  leafCount,
  makeLeaf,
  makeSplit,
  moveLeafRelativeToTarget,
  normalizeTree,
  planActivate,
  planCloseTab,
  planFocus,
  planHideLeaf,
  planMainSplitRatio,
  planMakeMain,
  planMovePane,
  planNestedSplitRatio,
  planReorder,
  planSetMode,
  planSplitLeaf,
  planTabHistory,
  preflightHideLeaf,
  preflightMakeMain,
  removeLeaf,
  repairWorkspaceState,
  replaceLeaf,
  replaceTabId,
  secondaryLeafCapReached,
  setSplitRatio,
  splitLeaf,
  validateTree,
  validateWorkspace,
  workspaceSnapshot,
} from './index'
